import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { RevisionPack, QuizResults } from '../types';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: typeof autoTable;
    lastAutoTable?: {
      finalY: number;
    };
  }
}

/**
 * PDF Export Utility
 * Provides functions to generate PDF documents from revision packs and quiz results
 */

const COLORS = {
  primary: '#4F46E5', // Indigo
  secondary: '#6B7280', // Gray
  success: '#10B981', // Green
  warning: '#F59E0B', // Amber
  error: '#EF4444', // Red
  text: '#1F2937', // Dark gray
  lightGray: '#F3F4F6',
};

const FONTS = {
  title: 20,
  heading: 16,
  subheading: 14,
  body: 11,
  small: 9,
};

/**
 * Add header to PDF page
 */
function addHeader(doc: jsPDF, title: string, pageNumber: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Header background
  doc.setFillColor(COLORS.primary);
  doc.rect(0, 0, pageWidth, 15, 'F');
  
  // Header text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(FONTS.small);
  doc.text(title, 10, 10);
  
  // Page number
  doc.text(`Page ${pageNumber}`, pageWidth - 30, 10);
  
  // Reset text color
  doc.setTextColor(COLORS.text);
}

/**
 * Add footer to PDF page
 */
function addFooter(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Footer line
  doc.setDrawColor(COLORS.secondary);
  doc.line(10, pageHeight - 15, pageWidth - 10, pageHeight - 15);
  
  // Footer text
  doc.setFontSize(FONTS.small);
  doc.setTextColor(COLORS.secondary);
  const footerText = `Generated by CramCraft - ${new Date().toLocaleDateString()}`;
  doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(COLORS.text);
}

/**
 * Add headers and footers to all pages
 */
function addHeadersAndFooters(doc: jsPDF, title: string): void {
  const pageCount = doc.getNumberOfPages();
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addHeader(doc, title, i);
    addFooter(doc);
  }
}

/**
 * Export revision pack as PDF
 */
export function exportRevisionPackPDF(revisionPack: RevisionPack): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPosition = 25; // Start below header space
  
  // Title page
  doc.setFontSize(FONTS.title);
  doc.setTextColor(COLORS.primary);
  doc.text('Revision Pack', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 10;
  doc.setFontSize(FONTS.body);
  doc.setTextColor(COLORS.secondary);
  doc.text(
    `Generated: ${revisionPack.generatedAt.toLocaleDateString()}`,
    pageWidth / 2,
    yPosition,
    { align: 'center' }
  );
  
  yPosition += 5;
  doc.text(
    `Estimated Reading Time: ${revisionPack.totalReadingTime} minutes`,
    pageWidth / 2,
    yPosition,
    { align: 'center' }
  );
  
  yPosition += 15;
  doc.setTextColor(COLORS.text);
  
  // Process each document
  revisionPack.documents.forEach((document, index) => {
    // Add page break between documents (except for first)
    if (index > 0) {
      doc.addPage();
      yPosition = 25;
    }
    
    // Document title
    doc.setFontSize(FONTS.heading);
    doc.setTextColor(COLORS.primary);
    doc.text(document.title, 10, yPosition);
    yPosition += 10;
    
    // Subject tag if present
    if (document.subject) {
      doc.setFontSize(FONTS.small);
      doc.setTextColor(COLORS.secondary);
      doc.text(`Subject: ${document.subject}`, 10, yPosition);
      yPosition += 8;
    }
    
    doc.setTextColor(COLORS.text);
    
    // Key Concepts section
    doc.setFontSize(FONTS.subheading);
    doc.setTextColor(COLORS.primary);
    doc.text('Key Concepts', 10, yPosition);
    yPosition += 7;
    
    doc.setFontSize(FONTS.body);
    doc.setTextColor(COLORS.text);
    document.keyConcepts.forEach((concept) => {
      const lines = doc.splitTextToSize(`• ${concept}`, pageWidth - 25);
      lines.forEach((line: string) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 25;
        }
        doc.text(line, 15, yPosition);
        yPosition += 5;
      });
    });
    
    yPosition += 5;
    
    // Definitions section
    if (document.definitions.length > 0) {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 25;
      }
      
      doc.setFontSize(FONTS.subheading);
      doc.setTextColor(COLORS.primary);
      doc.text('Important Definitions', 10, yPosition);
      yPosition += 7;
      
      doc.setFontSize(FONTS.body);
      doc.setTextColor(COLORS.text);
      
      document.definitions.forEach((def) => {
        if (yPosition > 260) {
          doc.addPage();
          yPosition = 25;
        }
        
        doc.setFont(undefined, 'bold');
        doc.text(`${def.term}:`, 15, yPosition);
        yPosition += 5;
        
        doc.setFont(undefined, 'normal');
        const defLines = doc.splitTextToSize(def.definition, pageWidth - 25);
        defLines.forEach((line: string) => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 25;
          }
          doc.text(line, 15, yPosition);
          yPosition += 5;
        });
        
        yPosition += 3;
      });
      
      yPosition += 5;
    }
    
    // Summary section
    if (yPosition > 200) {
      doc.addPage();
      yPosition = 25;
    }
    
    doc.setFontSize(FONTS.subheading);
    doc.setTextColor(COLORS.primary);
    doc.text('Summary', 10, yPosition);
    yPosition += 7;
    
    doc.setFontSize(FONTS.body);
    doc.setTextColor(COLORS.text);
    const summaryLines = doc.splitTextToSize(document.summary, pageWidth - 20);
    summaryLines.forEach((line: string) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 25;
      }
      doc.text(line, 10, yPosition);
      yPosition += 5;
    });
    
    yPosition += 5;
    
    // Memory Aids section
    if (document.memoryAids.length > 0) {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 25;
      }
      
      doc.setFontSize(FONTS.subheading);
      doc.setTextColor(COLORS.primary);
      doc.text('Memory Aids', 10, yPosition);
      yPosition += 7;
      
      doc.setFontSize(FONTS.body);
      doc.setTextColor(COLORS.text);
      
      document.memoryAids.forEach((aid) => {
        const aidLines = doc.splitTextToSize(`💡 ${aid}`, pageWidth - 25);
        aidLines.forEach((line: string) => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 25;
          }
          doc.text(line, 15, yPosition);
          yPosition += 5;
        });
      });
    }
  });
  
  // Add headers and footers to all pages
  addHeadersAndFooters(doc, 'CramCraft Revision Pack');
  
  // Download the PDF
  doc.save(`revision-pack-${new Date().getTime()}.pdf`);
}

/**
 * Export quiz results as PDF
 */
export function exportQuizResultsPDF(results: QuizResults): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPosition = 25; // Start below header space
  
  // Title
  doc.setFontSize(FONTS.title);
  doc.setTextColor(COLORS.primary);
  doc.text('Quiz Results', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  
  // Score summary box
  doc.setFillColor(COLORS.lightGray);
  doc.roundedRect(10, yPosition, pageWidth - 20, 30, 3, 3, 'F');
  
  yPosition += 10;
  doc.setFontSize(FONTS.heading);
  doc.setTextColor(COLORS.text);
  doc.text(
    `Score: ${results.score}/${results.totalQuestions} (${results.percentage}%)`,
    pageWidth / 2,
    yPosition,
    { align: 'center' }
  );
  
  yPosition += 8;
  
  // Readiness assessment with color
  const readinessColor =
    results.readinessColor === 'green'
      ? COLORS.success
      : results.readinessColor === 'yellow'
      ? COLORS.warning
      : results.readinessColor === 'orange'
      ? COLORS.warning
      : COLORS.error;
  
  doc.setFontSize(FONTS.body);
  doc.setTextColor(readinessColor);
  doc.text(results.readinessMessage, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  doc.setTextColor(COLORS.text);
  
  // Weak areas section
  if (results.weakAreas.length > 0) {
    doc.setFontSize(FONTS.subheading);
    doc.setTextColor(COLORS.primary);
    doc.text('Areas for Improvement', 10, yPosition);
    yPosition += 7;
    
    doc.setFontSize(FONTS.body);
    doc.setTextColor(COLORS.text);
    results.weakAreas.forEach((area) => {
      doc.text(`• ${area}`, 15, yPosition);
      yPosition += 6;
    });
    
    yPosition += 5;
  }
  
  // Question breakdown
  doc.addPage();
  yPosition = 25;
  
  doc.setFontSize(FONTS.heading);
  doc.setTextColor(COLORS.primary);
  doc.text('Question Breakdown', 10, yPosition);
  yPosition += 10;
  
  results.breakdown.forEach((item, index) => {
    // Check if we need a new page
    if (yPosition > 240) {
      doc.addPage();
      yPosition = 25;
    }
    
    // Question number and text
    doc.setFontSize(FONTS.subheading);
    doc.setTextColor(COLORS.text);
    doc.setFont(undefined, 'bold');
    doc.text(`Question ${index + 1}`, 10, yPosition);
    yPosition += 6;
    
    doc.setFontSize(FONTS.body);
    doc.setFont(undefined, 'normal');
    const questionLines = doc.splitTextToSize(item.question.question, pageWidth - 20);
    questionLines.forEach((line: string) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 25;
      }
      doc.text(line, 10, yPosition);
      yPosition += 5;
    });
    
    yPosition += 3;
    
    // User's answer
    const answerColor = item.isCorrect ? COLORS.success : COLORS.error;
    doc.setTextColor(answerColor);
    doc.text(`Your answer: ${item.userAnswer}`, 10, yPosition);
    yPosition += 5;
    
    // Correct answer if wrong
    if (!item.isCorrect) {
      doc.setTextColor(COLORS.success);
      doc.text(`Correct answer: ${item.question.correctAnswer}`, 10, yPosition);
      yPosition += 5;
    }
    
    // Explanation
    doc.setTextColor(COLORS.text);
    doc.setFont(undefined, 'italic');
    const explanationLines = doc.splitTextToSize(
      `Explanation: ${item.question.explanation}`,
      pageWidth - 20
    );
    explanationLines.forEach((line: string) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 25;
      }
      doc.text(line, 10, yPosition);
      yPosition += 5;
    });
    
    doc.setFont(undefined, 'normal');
    yPosition += 8;
  });
  
  // Add headers and footers to all pages
  addHeadersAndFooters(doc, 'CramCraft Quiz Results');
  
  // Download the PDF
  doc.save(`quiz-results-${new Date().getTime()}.pdf`);
}
